Repository klinker-apps/pulse-sms-web, pull requests merged in 2020-03, with the labels that each got.

#113 Only initialize bugsnag in production env
  package-lock.json
  src/main.js
  src/utils/util.js
Labels: bug

#116 Fix media loading failures causing worker to crash
  src/utils/media.js
Labels: bug

#118 Add conversation item ripple effect back
  src/components/Compose/Compose.vue
  src/components/Conversations/ConversationItem.vue
Labels: bug

#119 Update responsive conversation list
  src/components/Conversations/Conversations.vue
Labels: bug, enhancement

#121 Fix Snackbar -> snackbar issue
  src/components/Compose/Compose.vue
Labels: bug

#122 Fix registration error with service worker
  src/App.vue
Labels: bug

#123 Add version to bugsnag
  src/main.js
Labels: enhancement

#120 [#117] Add polyfill for notifications
  package.json
  src/App.vue
  src/components/Settings.vue
  src/utils/api/stream.js
  src/utils/util.js
Labels: bug, enhancement

#125 Fix/notifications
  src/App.vue
  src/utils/api/stream.js
  src/utils/index.js
  src/utils/notifications.js
  src/utils/platform.js
  src/utils/util.js
Labels: bug, enhancement

#126 Fix #search-bar is null error on /archived
  src/components/Conversations/Conversations.vue
Labels: bug

#129 Handle bad/invalid routes
  src/router/index.js
Labels: bug

#128 Fix bad thread id issues
  src/components/Thread/Thread.vue
Labels: bug

#131 Fix exception in cache on message deletion
  src/components/Thread/Thread.vue
  src/utils/api/stream.js
  src/utils/cache_manager.js
Labels: bug
